###Movie Index
GET http://localhost:3000/movies.json

###Movie Create
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "Movie",
  "year": 1999,
  "plot": "A movie",
  "director": "A person"
}

###Movie Show
GET http://localhost:3000/movies/2.json

###Movie Update
PATCH http://localhost:3000/movies/16.json
Content-Type: application/json

{
  "director": "abs"
}

###Movie Destroy
DELETE http://localhost:3000/movies/16

