###User Create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name" : "4Test",
  "email": "4Test@test.com",
  "password": "password",
  "password_confirmation": "password"
}